import Config

# Configure your database
config :treby, Treby.Repo,
  username: "postgres",
  password: "postgres",
  hostname: "localhost",
  database: "treby_dev",
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :treby, TrebyWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base:
    Treby.ConfigHelpers.env(
      "SECRET_KEY_BASE",
      "GJ/jN5Cfmi2lkFd8stz0oq3Dz5Ck78qojUy/hXnandfKeda4TeFVpTNckUYGRos9"
    ),
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:treby, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:treby, ~w(--watch)]}
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Reload browser tabs when matching files change.
config :treby, TrebyWeb.Endpoint,
  live_reload: [
    web_console_logger: true,
    patterns: [
      # Static assets, except user uploads
      ~r"priv/static/(?!uploads/).*\.(js|css|png|jpeg|jpg|gif|svg)$"E,
      # Gettext translations
      ~r"priv/gettext/.*\.po$"E,
      # Router, Controllers, LiveViews and LiveComponents
      ~r"lib/treby_web/router\.ex$"E,
      ~r"lib/treby_web/(controllers|live|components)/.*\.(ex|heex)$"E
    ]
  ]

# Enable dev routes for dashboard and mailbox
config :treby, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :default_formatter, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :phoenix_live_view,
  # Include debug annotations and locations in rendered markup.
  # Changing this configuration will require mix clean and a full recompile.
  debug_heex_annotations: true,
  debug_attributes: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true

# Disable swoosh api client as it is only required for production adapters.
config :swoosh, :api_client, false

# Configure RustFS (S3-compatible) for development
# Override with env vars when needed.
config :ex_aws, :s3,
  scheme: Treby.ConfigHelpers.env("S3_SCHEME", "http://"),
  host: Treby.ConfigHelpers.env("S3_HOST", "localhost"),
  port: String.to_integer(Treby.ConfigHelpers.env("S3_PORT", "9000")),
  access_key_id: Treby.ConfigHelpers.env("S3_ACCESS_KEY_ID", "treby"),
  secret_access_key: Treby.ConfigHelpers.env("S3_SECRET_ACCESS_KEY", "treby_password")

# Dev encryption key (32-byte key, base64-encoded).
# Override with CLOAK_KEY when needed.
config :treby,
  cloak_key: Treby.ConfigHelpers.env("CLOAK_KEY", "8TW7yfP2gTtJTBA6N2J7XEMzdeD6egoftgnnGzxISSk=")
